name: JuliaStable
on:
  push:
    branches:
      - main
      - staging
      - trying
  pull_request:

jobs:
  test:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      - name: Set up Actions
        uses: actions/checkout@v1
      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - name: Use Github Registry for Linux and Mac-OS
        if: runner.os != 'Windows'
        run: |
          julia -e 'using Pkg; Pkg.Registry.rm("General"); Pkg.Registry.add(RegistrySpec(url="https://github.com/JuliaRegistries/General"))'
          julia --project -e 'ENV["PYTHON"]=""; using Pkg; Pkg.instantiate();'
      - name: Use Github Registry for Windows
        if: runner.os == 'Windows'
        run: |
          julia -e 'using Pkg; Pkg.Registry.rm(\"General\"); Pkg.Registry.add(RegistrySpec(url=\"https://github.com/JuliaRegistries/General\"))'
          julia --project -e 'ENV[\"PYTHON\"]=\"\"; using Pkg; Pkg.instantiate();'
      - name: Run Tests
        uses: julia-actions/julia-runtest@latest
      - name: Process Coverage
        if: runner.os == 'Linux'
        uses: julia-actions/julia-processcoverage@v1
      - name: Submit Coverage
        if: runner.os == 'Linux'
        uses: codecov/codecov-action@v1
        with:
          file: lcov.info
